# Generated by Django 5.0.1 on 2025-09-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_fuellayer_moisturelayer_scenariotag_checkpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="checkpoint_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="pause_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="paused_at_tick",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
